### ISSUE TITLE
access a getter spy error

### ISSUE THREAD

**Issue by unlight** [henrysun918/mock-factory#6]
```
var AppService = /** @class */ (function () {
    function AppService() {
        this.appInitialized$ = new BehaviorSubject(false);
    }
    Object.defineProperty(AppService.prototype, "isAppInitialized", {
        get: function () {
            return this.appInitialized$.getValue();
        },
        enumerable: true,
        configurable: true
    });
```
```
const appService = MockFactory.create(AppService);
appService ._spy.isAppInitialized._get.and.returnValue(true);
```
```
TypeError: Cannot read property 'getValue' of undefined
```

```
           // if target is property
            if (typeof this.prototype[propertyName] !== 'function') { // <--- error here
                // we add getters and setters to all properties to make the read and write spy-able
                var descriptor = {
                    get: /* istanbul ignore next: Can't reach. spyOnProperty() requires its presence to install spies */ function () { },
                    set: /* istanbul ignore next: Can't reach. spyOnProperty() requires its presence to install spies */ function (value) { },
                    enumerable: true,
                    configurable: true,
                };
```
Why `Object.getOwnPropertyDescriptors(this.prototype)[propName]` is not used?

**Comment by chuanqisun** [comment]
I remember trying getOwnPropertyDescriptor. It would miss properties that are not getter/setter. I think it would also miss inherited properties.

I couldn't repro your issue. Do you have more details? How come 'getValue' is used?  Maybe set up a minimum repro to demonstrate? The code below works for me with no errors. Is Rxjs working as expected?
```
import { MockFactory, Mock } from './index';

var AppService = /** @class */ (function () {
    function AppService() {
        this.appInitialized$ = {}
    }
    Object.defineProperty(AppService.prototype, "isAppInitialized", {
        get: function () {
            return this.appInitialized$.getValue();
        },
        enumerable: true,
        configurable: true
    });

    return AppService;
});


describe('', () => {
    it('', () => {
        let mockAppService = MockFactory.create(AppService);
        mockAppService._spy.isAppInitialized._get.and.returnValue(true);

        expect((mockAppService as any).isAppInitialized).toBe(true);
    });
});
```

**Comment by unlight** [comment]
I added simplified example in my fork:
https://github.com/unlight/jasmine-mock-factory/tree/henrysun918_jasmine-mock-factory-6

```
import { MockFactory, Mock } from './index';

class AppService {

    appInitialized$ = { value: 42 };

    get isAppInitialized() {
        return this.appInitialized$.value === 42;
    }

}

describe('class getter', () => {

    fit('access to getter using other class properties', () => {
        let mockAppService = MockFactory.create(AppService);
        mockAppService._spy.isAppInitialized._get.and.returnValue(true);
        expect((mockAppService as any).isAppInitialized).toBe(true);
    });

});

````
```
Chrome 61.0.3163 (Windows 8.1 0.0.0) class getter access to getter using other class properties FAILED
        TypeError: Cannot read property 'value' of undefined
            at Object.get [as isAppInitialized] (http://localhost:9876/_karma_webpack_/main.bundle.js:41:41)
            at DynamicBase.webpackJsonp../src/lib/index.ts.DynamicBase.ensureSpy (http://localhost:9876/_karma_webpack_/main.bundle.js:1034:38)
            at Object.get (http://localhost:9876/_karma_webpack_/main.bundle.js:1019:23)
```

**Comment by chuanqisun** [comment]
Thanks. This is a bug indeed. When I call `if (typeof this.prototype[propertyName] !== 'function')`, I'm invoking the native getter to check if it is a function, and if the native getter depends on some other property, that property will be undefined.

My planned fix is to remove all the native getter behaviors when constructing the mock. This is not trivial and might take a while.

In the meanwhile, maybe try a workaround that manually provides the mocked value in `appInitialized$` before you setup the getter? Something like this:
```
    it('', () => {
        let mockAppService = MockFactory.create(AppService);
        mockAppService._spy.appInitialized$._get.and.returnValue(MockFactory.create(BehaviorSubject));
        mockAppService._spy.isAppInitialized._get.and.returnValue(true);

        expect((mockAppService as any).isAppInitialized).toBe(true);
    });
```

**Comment by chuanqisun** [comment]
I have a better fix. I use `try...catch...` when checking if a member is a getter/setter property or a function. If an error is thrown, I catch it and assumes it is a getter property. You can get the fix in version `2.0.3` that I just published.

I feel `try...catch...` might be the only solution since I can't find any way to test wheter a property is a getter/setter or a function without potentially invoking a getter.

Cheers!

**Comment by unlight** [comment]
> try...catch... might be the only solution since I can't find any way to test wheter a property is a 

Actually, it's a quite easy by `Object.getOwnPropertyDescriptor`
```js
const descriptor = Object.getOwnPropertyDescriptor(this.prototype, propertyName);
if (descriptor === undefined) {
  // propertyName does not exists
} else if ('value' in descriptor) {
  if (typeof descriptor.value === 'function') { // it's safe to check for function
    // property is function
  }
  // ...
} else if (descriptor.get || descriptor.set) {
  // property getter or setter
}
```
[getOwnPropertyDescriptor](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/getOwnPropertyDescriptor)

**Comment by chuanqisun** [comment]
I think that wouldn't work on inherited properties.
